package io.github.jbellis.brokk.analyzer;

import java.nio.file.Path;
import java.util.Locale;
import java.util.Set;
import java.util.HashSet;
import java.util.Arrays;

public class FileExtensions {
    public static boolean matches(Path path, String extension) {
        return path.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(extension.toLowerCase(Locale.ROOT));
    }

    public static final Set<String> IMAGE_EXTENSIONS = new HashSet<>(Arrays.asList(
            // Raster formats
            ".ani", ".anim", ".apng", ".art", ".avif", ".bmp", ".bpg", ".bsave", ".cal", ".cin",
            ".cpc", ".cpt", ".dds", ".dpx", ".ecw", ".exr", ".fits", ".flic", ".flif", ".fpx",
            ".gif", ".hdri", ".hevc", ".icer", ".icns", ".ico", ".cur", ".ics", ".ilbm", ".jbig",
            ".jbig2", ".jng", ".jpeg", ".jpeg_ls", "jpeg_2000", "jpeg_xl", "jpeg_xr",
            "jpeg_xs", "jpeg_xt", "jpeg-hdr", "kra", ".mng", ".miff", ".nrrd", ".ora", ".pam",
            ".pbm", ".pgm", ".ppm", ".pnm", ".pcx", ".pgf", ".pictor", ".png", ".psd", ".psb",
            ".psp", ".qoi", ".qtvr", ".ras", ".rgbe", ".logluv", ".tiff", ".sgi", ".tga",
            ".tiff_ep", "tiff_it", "ufo", ".ufp", ".wbmp", ".webp", ".xbm", ".xcf", ".xpm", ".xwd",

            // Raw formats
            ".ciff", ".dng",

            // Vector formats
            ".ai", ".cdr", ".cgm", ".dxf", ".emf", ".emf+", "gerber", ".hvif", ".iges", ".pgml",
            ".svg", ".vml", ".wmf", ".xar",

            // Compound formats
            ".cdf", ".djvu", ".eps", ".modca", ".pdf", ".pict", ".ps", ".swf", ".xaml",

            // Metadata-related
            ".exif", ".xmp"
    ));

    public static final Set<String> TEXT_EXTENSIONS = new HashSet<>(Arrays.asList(
            ".as",
            ".adb",
            ".ads",
            ".agda",
            ".ino",
            ".asm",
            ".s",
            ".astro",
            ".bash",
            ".sh",
            ".zsh",
            ".bean",
            ".bib",
            ".bicep",
            ".bb",
            ".bbappend",
            ".bbclass",
            ".c",
            ".h",
            ".cairo",
            ".capnp",
            ".chatito",
            ".clar",
            ".clj",
            ".cljc",
            ".cljs",
            ".edn",
            ".cmake",
            ".txt",
            ".cl",
            ".lisp",
            ".cpon",
            ".cc",
            ".cpp",
            ".cxx",
            ".h++",
            ".hpp",
            "..hxx",
            ".cs",
            ".css",
            ".csv",
            ".cu",
            ".cuh",
            ".d",
            ".dart",
            ".dtd",
            ".el",
            ".ex",
            ".exs",
            ".elm",
            ".erl",
            ".hrl",
            ".fnl",
            ".fir",
            ".fish",
            ".f",
            ".f03",
            ".f08",
            ".f90",
            ".f95",
            ".fc",
            ".gd",
            ".gitattributes",
            ".gitcommit",
            ".gitignore",
            ".gleam",
            ".frag",
            ".glsl",
            ".vert",
            ".gn",
            ".gni",
            ".go",
            ".mod",
            ".sum",
            ".groovy",
            ".launch",
            ".hack",
            ".ha",
            ".hs",
            ".hx",
            ".hcl",
            ".tf",
            ".tfvars",
            ".heex",
            ".hlsl",
            ".htm",
            ".html",
            ".hypr",
            ".ispc",
            ".janet",
            ".java",
            ".js",
            ".jsx",
            ".mjs",
            ".jsdoc",
            ".json",
            ".jsonnet",
            ".libsonnet",
            ".jl",
            ".kdl",
            ".kt",
            ".kts",
            ".cls",
            ".sty",
            ".tex",
            ".ld",
            ".ll",
            ".lua",
            ".luadoc",
            ".luap",
            ".luau",
            ".magik",
            ".mk",
            ".markdown",
            ".md",
            ".m",
            ".mat",
            ".mermaid",
            ".build",
            ".ninja",
            ".nix",
            ".nqc",
            ".mm",
            ".odin",
            ".org",
            ".pas",
            ".pp",
            ".pem",
            ".pl",
            ".pm",
            ".pgn",
            ".php",
            ".po",
            ".pot",
            ".pony",
            ".ps1",
            ".psm1",
            ".printf",
            ".prisma",
            ".properties",
            ".proto",
            ".psv",
            ".purs",
            ".in",
            ".py",
            ".qml",
            ".R",
            ".r",
            ".rkt",
            ".re2c",
            ".inputrc",
            ".ron",
            ".rst",
            ".rb",
            ".rs",
            ".sc",
            ".scala",
            ".scm",
            ".ss",
            ".scss",
            ".smali",
            ".smithy",
            ".sol",
            ".rq",
            ".sql",
            ".nut",
            ".bzl",
            ".svelte",
            ".swift",
            ".td",
            ".tcl",
            ".thrift",
            ".toml",
            ".tsv",
            ".twig",
            ".ts",
            ".tsx",
            ".typ",
            ".rules",
            ".ungram",
            ".tal",
            ".sv",
            ".v",
            ".vhd",
            ".vhdl",
            ".vim",
            ".vimrc",
            ".vue",
            ".wgsl",
            ".XCompose",
            ".svg",
            ".xml",
            ".xsl",
            ".yuck",
            ".zig"
    ));
}
